# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 911f4992393abb50f5b15b8b362eda19443030f13dce37506df6294729bdc5cf71f57b4bcdfdb500f4b6751875c5cb9ac13ab84005d3a9fbcf2959aaefc7a84d

test:
  secret_key_base: c211b4e3a29d3cfb8371997b817eee54b2a67ad6917aa84e5335bdc4ec89b34691c1b54d5479f0b94ded49dbc4fe80fbde50cbb7e3a8628e038125d66a44800e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
